image: alpine/edge
# We use rustup and manually install Rust for each step, b/c the rust
# package doesn't update that quickly
packages:
  - rustup
  - just
sources:
  - git@git.sr.ht:~jangermad/magus
secrets:
  - b3a02cf9-8da6-4caa-a4c9-833027656007
tasks:
  - run-rustup: |
      rustup-init --profile minimal --default-toolchain stable -y
      cat magus/.buildenv | tee -a ~/.buildenv
  - install-deps: |
      curl -LsSf https://get.nexte.st/latest/linux-musl | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin
      cargo install icu_datagen
  - run-tests: |
      cd magus
      just test-ci
  - build-wasm: |
      cd magus
      just build-wasm
