[workspace]
resolver = "2"
members = [".", "datatest_parse", "magus_format", "magus_repl"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"

[package]
name = "magus"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
description = "R7RS-scheme implementation in Rust using gc-arena"

[[test]]
name = "datatests"
harness = false

[[bench]]
name = "library_name"
harness = false

[dependencies]
anyhow = "1.0.91"
arbitrary = { version = "1", features = ["derive"] }
fxhash = "0.2.1"
gc-arena = { git = "https://github.com/kyren/gc-arena", rev = "d18259e33bd360beb6f8e07a86fc774512aec965" }
icu_casemap = "1.5.1"
lasso = { version = "0.7.2" }
logos = { version = "0.15" }
paste = "1.0.15"
# petgraph = "0.6.5"
rowan = "0.16"
slotmap = "1.0.7"
thiserror = "2"

[dev-dependencies]
arbtest = "0.3.1"
assert2 = "0.3.15"
datatest-stable = "0.3.2"
datatest_parse = { path = "datatest_parse" }
divan = "0.1.17"
rstest = "0.24.0"
