[workspace]
resolver = "2"
members = [".", "magus_repl"]

[workspace.package]
version = "0.1.0"
rust-version = "1.80"

[package]
name = "magus"
version.workspace = true
rust-version.workspace = true
edition = "2021"
description = "R5RS-scheme implementation in Rust using gc-arena"

[[test]]
name = "frontend_datatest"
harness = false

[dependencies]
anyhow = "1.0.91"
arbitrary = { version = "1", features = ["derive"] }
either = "1.13.0"
gc-arena = { git = "https://github.com/kyren/gc-arena", rev = "a7638dcb0ebb0525f4fa69638c4790fe989fe073" }
icu_casemap = "1.5.1"
lasso = { version = "0.7.2" }
logos = { version = "0.14.1" }
paste = "1.0.15"
# petgraph = "0.6.5"
rowan = "0.15.15"
slotmap = "1.0.7"
thiserror = "1.0.63"

[dev-dependencies]
arbtest = "0.3.1"
assert2 = "0.3.15"
datatest-stable = "0.2.9"
