let impled = '&#x2705;'
let not_impled  = '&#x274C;'
let partial_impled = '&#x1F7E1;'
let never_impled = '&#x1F645;'

let data = open compatibility.nuon

def data_total [with_status: any]: table -> int {
  $data | where impl-status == $with_status | reduce -f 0 {|it, acc| $acc + 1}
}

let implemented = $data | data_total true
let with_partial = ($data | data_total true) + ($data | data_total partial)
let total = ($data | length) - ($data | data_total never)

let prelude = $"# Compatibility

Generated by gen_compatibility_doc.nu on (date now | format date '%B %d, %Y %H:%M:%S%.3f')

Overall Status: ($implemented) \(($with_partial)) / ($total)

## Legend
- Implemented: ($impled)
- Partially Implemented: ($partial_impled)
- Not Implemented: ($not_impled)
- Never To Be Implemented: ($never_impled)

Never To Be Implemented marks functionality that will not be implemented by our standard library
\(an application can feel free to include an implementation for such functionality as they please.)
"

let sections = ($data | sort-by identifier | group-by library --to-table )

def is_empty []: string -> bool {
  ($in | default '' | str length) == 0
}

def escape_html []: string -> string {
  $in |
    str replace --all '&' '&amp;' |
    str replace --all '<' '&lt;' |
    str replace --all '>' '&gt;' 
}
def upcase_scheme []: string -> string {
  if $in =~ "(?i)R\\dRS" {
    $in | str upcase
  } else if $in =~ '(?i)srfi \d+' {
    $in | str upcase
  } else {
    $in
  }
}

def library_name []: string -> string {
  if $in =~ '(?i)srfi \d+' {
    $in
  } else {
    $"scheme ($in)"
  }
}

let section_format = {|it|
$"### (if ($it.impl-type | is_empty) {"symbol"} else {$it.impl-type} | str capitalize) `\(($in.library | library_name))`: _($it.identifier | into string | escape_html)_
- Implementation status: (match $it.impl-status { true => {($impled)}, never => {($never_impled)}, partial => {($partial_impled)}, _ => {($not_impled)}})
- _(if ($it.description | is_empty) { 'No description' } else { $it.description })_
(if ($it.notes? | is_empty) {''} else {$"\n($it.notes)"})
"}

let section_text = $sections | where library !~ '(?i)srfi \d+' | sort-by library | each {
let all_impled = ($in.items | all { $in.impl-status == true})
let all_nevered = ($in.items | all { $in.impl-status == never})
let impl_mark = if $all_impled { $" ($impled)" } else if $all_nevered { $" ($never_impled)" } else { "" }
$"## Scheme Standard: ($in.library | str title-case | upcase_scheme) Library `\(($in.library | library_name)\)`($impl_mark)
($in.items | each $section_format | str join "\n")"};

let srfi_section_text = $sections | where library =~ '(?i)srfi \d+' | sort-by library | each {
let all_impled = ($in.items | all { $in.impl-status == true})
let all_nevered = ($in.items | all { $in.impl-status == never})
let impl_mark = if $all_impled { $" ($impled)" } else if $all_nevered { $" ($never_impled)" } else { "" }
$"## Scheme SRFI: ($in.library | str title-case | upcase_scheme) Library `\(($in.library | library_name)\)`($impl_mark)
($in.items | each $section_format | str join "\n")"};

[$prelude] ++ $section_text ++ $srfi_section_text  | str join "\n"
