[package]
name = "demosite"
version = "0.1.0"
edition = "2024"
rust-version = "1.86"

[dependencies]
anyhow = "1.0.98"
codee = { version = "0.3.0", features = ["json_serde_wasm", "base64"] }
console_error_panic_hook = "0.1.7"
console_log = "1.0.0"
getrandom = { version = "0.3", features = ["wasm_js"] }
leptos = { version = "0.8.2", features = ["csr"] }
leptos-use = "0.16"
log = "0.4.27"
magus = { version = "0.1.0", path = ".." }
phosphor-leptos = "0.8.0"
serde = { version = "1.0.219", features = ["derive"] }
syntect = { version = "5.2", default-features = false, features = ["fancy-regex", "default-fancy", "html"] }
ulid = "1.2.1"
wasm-bindgen = "=0.2.100"
web-sys = { version = "0.3.77", features = ["HtmlTextAreaElement"] }
