[package]
name = "magus_repl"
edition = "2021"
version.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.16", features = ["derive"] }
codesnake = "0.2.1"
magus = { version = "0.1.0", path = ".." }
yansi = { version = "1.0.1", features = ["detect-env", "detect-tty"] }
gc-arena = { git = "https://github.com/kyren/gc-arena", rev = "5a7534b883b703f23cfb8c3cfdf033460aa77ea9" }
reedline = { version = "0.37.0", features = ["sqlite", "system_clipboard"] }
