name: CI

on:
  push:
    branches: [trunk]
  pull_request:
    branches: [trunk]

env:
  CARGO_TERM_COLOR: always

jobs:
  arbtest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v1
      - name: Install nextest
        uses: taiki-e/install-action@nextest
      - name: Run arbtests
        run: cargo nextest r -E "test(arbtest)" --verbose --success-output=final
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v1
      - name: Install nextest
        uses: taiki-e/install-action@nextest
      - name: Install icu_datagen
        uses: taiki-e/install-action@icu_datagen
      - name: Add WASM target
        run: rustup target add wasm32-unknown-unknown
      - name: Build for wasm
        run: just build-wasm
      - name: Run tests
        run: cargo nextest r -E "not test(arbtest)" --verbose --success-output=final
