name: CI

on:
  push:
    branches: [trunk]
  pull_request:
    branches: [trunk]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v1
      - name: Add WASM target
        run: rustup target add wasm32-unknown-unknown
      - name: Build for wasm
        run: just build-wasm
      - name: Run tests
        run: cargo test --verbose
